###
# This file helps to setup a local environment
# for development as well as testing
###
version: '3.1'

services:

  postgres:
    image: postgres:12
    volumes:
      - ./.tmp/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
      POSTGRES_DB: overseer
    ports:
      - 5445:5432

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - 8082:80

  redis:
    image: redis:6
    volumes:
      - ./.tmp/redis:/data
    ports:
      - 6379:6379
